// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa995pRfxyjB7BYm1hfEzwnuUOETFV6e8',
    appId: '1:183693223508:web:cbce43af3f424c1e802fc1',
    messagingSenderId: '183693223508',
    projectId: 'demo1-6c646',
    authDomain: 'demo1-6c646.firebaseapp.com',
    storageBucket: 'demo1-6c646.appspot.com',
    measurementId: 'G-RZE43CV0PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVl8RFie6-OAatnoKwb7xKTKJcQQB48As',
    appId: '1:183693223508:android:512ceed15ebe95c3802fc1',
    messagingSenderId: '183693223508',
    projectId: 'demo1-6c646',
    storageBucket: 'demo1-6c646.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE30rAKPvm4x_sjIiax9VBIBHno6APzkI',
    appId: '1:183693223508:ios:976c16e4b00ec829802fc1',
    messagingSenderId: '183693223508',
    projectId: 'demo1-6c646',
    storageBucket: 'demo1-6c646.appspot.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE30rAKPvm4x_sjIiax9VBIBHno6APzkI',
    appId: '1:183693223508:ios:4d23e8c188b3029f802fc1',
    messagingSenderId: '183693223508',
    projectId: 'demo1-6c646',
    storageBucket: 'demo1-6c646.appspot.com',
    iosBundleId: 'com.example.demo1.RunnerTests',
  );
}
